# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: b.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x07\x62.proto\"\x9d\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x1e\n\x05genre\x18\x04 \x01(\x0e\x32\x0f.Book.GenreType\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\"0\n\tGenreType\x12\x0b\n\x07\x43LASSIC\x10\x00\x12\t\n\x05\x43RIME\x10\x01\x12\x0b\n\x07\x46\x41NTASY\x10\x02\"\x85\x01\n\rInventoryItem\x12\n\n\x02id\x18\x01 \x02(\x05\x12\x15\n\x04\x62ook\x18\x04 \x01(\x0b\x32\x05.BookH\x00\x12%\n\x06status\x18\x02 \x01(\x0e\x32\x15.InventoryItem.Status\"\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04Item\"\xaf\x01\n\rCreateRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\'\n\x05genre\x18\x04 \x01(\x0e\x32\x18.CreateRequest.GenreType\x12\x16\n\x0epublishingYear\x18\x05 \x01(\x05\"0\n\tGenreType\x12\x0b\n\x07\x43LASSIC\x10\x00\x12\t\n\x05\x43RIME\x10\x01\x12\x0b\n\x07\x46\x41NTASY\x10\x02\"!\n\x0e\x43reateResponse\x12\x0f\n\x07\x43reated\x18\x01 \x02(\x08\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x02(\x05\"5\n\x0fGetBookResponse\x12\r\n\x05\x45xist\x18\x01 \x02(\x08\x12\x13\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.Book2s\n\x10InventoryService\x12/\n\nCreateBook\x12\x0e.CreateRequest\x1a\x0f.CreateResponse\"\x00\x12.\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponse\"\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'b_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=12
  _BOOK._serialized_end=169
  _BOOK_GENRETYPE._serialized_start=121
  _BOOK_GENRETYPE._serialized_end=169
  _INVENTORYITEM._serialized_start=172
  _INVENTORYITEM._serialized_end=305
  _INVENTORYITEM_STATUS._serialized_start=263
  _INVENTORYITEM_STATUS._serialized_end=297
  _CREATEREQUEST._serialized_start=308
  _CREATEREQUEST._serialized_end=483
  _CREATEREQUEST_GENRETYPE._serialized_start=121
  _CREATEREQUEST_GENRETYPE._serialized_end=169
  _CREATERESPONSE._serialized_start=485
  _CREATERESPONSE._serialized_end=518
  _GETBOOKREQUEST._serialized_start=520
  _GETBOOKREQUEST._serialized_end=550
  _GETBOOKRESPONSE._serialized_start=552
  _GETBOOKRESPONSE._serialized_end=605
  _INVENTORYSERVICE._serialized_start=607
  _INVENTORYSERVICE._serialized_end=722
# @@protoc_insertion_point(module_scope)
